### ISSUE TITLE
Option to delete output file before updating

### ISSUE THREAD

**Issue by danvk** [substack/watchify#158]
In the 1-2s it takes to do an update, the output bundle will be stale. It would be nice if there were an option to delete the output bundle during the update. This would make refreshing a page that sourced the bundle produce a clear error, rather than stale content.

**Comment by zertosh** [comment]
When building from the command-line there is an [extra step](https://github.com/substack/watchify/blob/ae3a71cc55ce49d7f3ee27db23cb2aba76a2efdb/bin/cmd.js#L38-L45) to ensure that you're served stale content instead of an error (due to partial content).

If you want to make your rebuilds _faster_, you can try lowering the `delay`. The default is 600ms. You can use `--delay` or pass in `opts.delay`.
