### ISSUE TITLE
outpipe is breaking a couple of my tests

### ISSUE THREAD

**Issue by mattdesl** [substack/watchify#184]
I've noticed 3.1.0 has broken a couple of tests of mine. The file is zero-length immediately after the update event. Here is a test case that works in 3.0.1, but breaks in 3.1.0:

```js
var fs = require('fs')
var path = require('path')
var spawn = require('npm-execspawn')

var proc = spawn(['watchify', '-o', 'bundle.js', '-v'].join(' '))
proc.stderr.on('data', function(data) {
  console.log("got update")
  fs.readFile(path.join(__dirname, 'bundle.js'), 'utf8', function(err, data) {
    if (err) throw err
    console.assert(data.length !== 0)
  })
})
```

Maybe outpipe should only be used when `>` or `|` is detected in the `--outfile` argument? Not sure how robust that is.

**Comment by zertosh** [comment]
Ah, yeah, this happens because of how outpipe writes to a file.

outpipe is exec'ing `echo > bundle.js` (where `echo` is actually a node script with `process.stdin.pipe(process.stdout);`), and returning the `stdin` of the exec. In `cmd.js`, we're [waiting for a `close` event](https://github.com/substack/watchify/blob/e20c9a39fad48f411b2dc48a1d784a947bb8fb9e/bin/cmd.js#L41) on that `stdin`. That `close` happens when browserify is done piping data into that stream, not when it's done. What we really need is the `exit` on the exec, which outpipe is [kind enough to proxy](https://github.com/substack/outpipe/blob/974c973abecb99428c77e6b93ddaa3d162b9ac8f/index.js#L28). This should be enough to fix it, but I can't throughly test it until Sunday :disappointed: 

``` diff
diff --git a/bin/cmd.js b/bin/cmd.js
index 9ff6f8fb..9c2f832a 100755
--- a/bin/cmd.js
+++ b/bin/cmd.js
@@ -26,6 +26,9 @@ function bundle () {
     var outStream = process.platform === 'win32'
         ? fs.createWriteStream(outfile)
         : outpipe(outfile);
+    var outDoneEvent = process.platform === 'win32'
+        ? 'close'
+        : 'exit';
 
     var wb = w.bundle();
     wb.on('error', function (err) {
@@ -38,7 +41,7 @@ function bundle () {
     outStream.on('error', function (err) {
         console.error(err);
     });
-    outStream.on('close', function () {
+    outStream.on(outDoneEvent, function () {
         if (verbose && !didError) {
             console.error(bytes + ' bytes written to ' + outfile
                 + ' (' + (time / 1000).toFixed(2) + ' seconds)'
```

**Comment by mattdesl** [comment]
No worries. I'm switching budo to use the watchify API anyways. 

If I get a chance this weekend I can test and PR. Have a good one

**Comment by substack** [comment]
Updated outpipe upstream to only `exec()` when `>` or `|` operators are used. Otherwise it just does `fs.createWriteStream()`.

**Comment by mattdesl** [comment]
Fixed upstream
