### ISSUE TITLE
Watchify not rebuilding when certain files change

### ISSUE THREAD

**Issue by XemsDoom** [substack/watchify#217]
Hi, I have an issue where watchify doesnt trigger a rebuild.

I am using following versions:
* nodejs 0.12.2
* browserify 10.0.0
* watchify 3.2.1
* Windows 7 64bit

We have the following dependency chain:
client.js (main file) <- Router.js <- CRMContractView.js

Changing `CRMContractView.js` triggers Babel to transpile the file into an ES5 one in a target directory. Watchify is setup to watch over that directory. However, it does not trigger any rebuild. If I however change `Router.js` watchify retriggers a rebuild.

Gulp is doing following process:
* Watch over files in `src/` directory with gulp-watch
* Transpile ES6 files from `src/` to ES5 in `target/` via Babel
* Bundle all files from `target/` via watchify/browserify

Note, I don't have any gulp-plumber setup, so it should throw an error if something would be wrong.
Following GIF shows you the console, I am hitting ctrl+s in ST3 first in `CRMContractVIew.js` and then in `Router.js`:
![gifgif](http://i.imgur.com/9A8P1cF.gif)

This is my current gulpfile (parts which matter):
```
gulp.task('transpileClientJS', function(){
	gulp.src(sourcePaths.client.js)
	.pipe(watch(sourcePaths.client.js))
	.pipe(debug({title: 'babel transpile'}))
	.pipe(babel())
	.pipe(gulp.dest(destPaths.client.js));
});

function setupBrowserify(){

	// browserify gets a little more complicated
	var customOpts = {
		entries: [destPaths.client.entryPoint],
		debug: true,
		poll: 300
	};
	var opts = _.assign({}, watchify.args, customOpts);
	var bundler = watchify(browserify(opts));
	bundler.on('update', bundle);
	bundler.on('log', gutil.log);
	bundler.on('error', gutil.log);

	function bundle(){
		return bundler.bundle()
		.on('error', gutil.log.bind(gutil, 'Browserify Error'))
		.pipe(source('bundle.js'))
		.pipe(gulp.dest(destPaths.client.browserifyTarget))
		.pipe(livereload());
	}
	bundle();
}

gulp.task('browserify', setupBrowserify);
```

Additional infos:
* I've set `poll` to 300 for testing but it doesn't change the behavior.
* What's strange is that another file with the same dependency chain actually retriggers a rebuild.
* Watchify is watching 55 files in 22 folders.
* All files or folders are no symlinks and are neither on a network drive.
* The initial bundling works when I startup gulp, so it sounds like watchify is not seeing the file change
* As mentioned above, changing `Router.js` also bundles up the changes I did in `CRMContractView.js`

**Edit**: it's actually random, if I restart gulp and then change `CRMContractView.js` it retriggers a rebuild but if I change the other file with the same dependency chain it does not?!

Any ideas what is causing the problem?

**Comment by zertosh** [comment]
A couple of things, in no particular order:

* watchify works by only watching the files that your build explicitly requires - not whole directories. It seems that your files are all part of the same dep graph so that's not it.
* I noticed that when you saved a file, and babel transpiled it, that it logged multiple times. Maybe you have multiple watchers? And that's messing things up?
* I'm not sure what method babel uses to write files to disk (I know I should know this, but I don't use it like that), but that could also be a problem. watchify sometimes has problems with "safe writes"/"atomic writes" (saving the file under a temp name and then renaming it). That could be what Babel is doing.
  * You're better off using the [babelify](https://github.com/babel/babelify) transform instead. That way you don't have multiple watchers. That might help.
  * If you're doing the babel write to disk thing because you need the same files on the server, consider using the [require hook](https://babeljs.io/docs/usage/require/) instead. That way you don't have another watcher running.

**Comment by XemsDoom** [comment]
In the order:
* As you said, yes all files require each other in a way, so that's not the problem
* That's just me hitting ctrl+s multiple times (a lot) and it not caused by multiple watchers
* I need the ES5 files in the target directory because when I build the project I simply browserify those files and then uglify them. During development, the target bundle.js file is not compressed.

I will test however, if babelify fixes the problem and will give you a report back in this issue.
Thanks for your help.
