### ISSUE TITLE
Node process runs forever, even after w.close()

### ISSUE THREAD

**Issue by callumlocke** [substack/watchify#22]
Using watchify's JavaScript API, is there any way to stop the watcher programatically?

**Comment by zertosh** [comment]
This shouldn't be a problem after v2.5.0. The `fs.lstat` isn't done anymore. See https://github.com/substack/watchify/pull/160.

**Comment by J-Zeitler** [comment]
I still don't really get how this is supposed to work, given that @zertosh is right. In my head the solution posted above:

```javascript
w.on('time', function() {
    w.close();
});
````

is a nice, straight forward way of closing all watchers. It should be simple, but I cannot get it to work.

Have anyone else got it running on OSX?

I tried to debug watchify telling it not to add watchers if it had gotten a close signal, but that does not prevent it from persisting. My bet is that the problem is somewhere in [chokidar](https://github.com/paulmillr/chokidar) or [fsevents](https://github.com/strongloop/fsevents) as indicated [here](https://github.com/paulmillr/chokidar/issues/217).

Tried to upgrade to latest chokidar and latest fsevents, but no luck.

**Comment by zertosh** [comment]
@J-Zeitler Sorry, I didn't read the entire thread. I think the chokidar/fsevents is now fixed. I just ran a quick test on watchify@3.1.0 with chokidar@1.0.0-rc5 . `w.close()` does release all the watchers and the process does end.

You could also try [this](https://github.com/substack/watchify/blob/master/test/zzz.js) hack. That's the last test that runs (because of the alpha sorting) for watchify. It's just a timeout and then it manually ends the process. It's gross but it works too.
