### ISSUE TITLE
A minor update to cover updating browserify to a new major!?

### ISSUE THREAD

**Issue by Nathan219** [substack/watchify#253]
Why did you guys update browserify to a new major version, but only consider it a minor for this?  This change totally messed up our development since another package, grunt-browserify, uses this.

https://github.com/jmreidy/grunt-browserify/issues/343

We had to revert back to watchify to 3.2.2 to get watching back.  That should have been considered a breaking change, since browserify did.

**Comment by substack** [comment]
The watchify API doesn't include browserify directly: https://github.com/substack/watchify/blob/master/index.js

Only the command-line version depends on browserify directly, and these changes do not surface in the command-line version: https://github.com/substack/watchify/blob/master/bin/args.js#L1

Bumping browserify was in response to fixes that landed upstream. Wrapper modules like grunt-browserify are always going to be a difficult case because they take on the task of versioning for packages that are meant to be consumed directly.
