### ISSUE TITLE
watchify drops out

### ISSUE THREAD

**Issue by loldrup** [substack/watchify#299]
My watchify installation seems to only detect file changes sometimes. It works for a few minutes and after that it just doesn't respond to file changes anymore.

I run watchify like this:

    watchify js/test.js -o js/test_bundle.js --debug

I'm on windows 7, and all my packages are very recently installed, as I have only just started using node.

**Comment by zertosh** [comment]
Since it works for a few minutes but then it doesn't, that sounds like a [chokidar](https://github.com/paulmillr/chokidar) issue. It may be a windows thing. I'd try looking through the issues there. I'd also try turning on [polling](https://github.com/substack/watchify#options) since that usually gets around any system issues.
